world:
  name: world
  spawn:
    x: -55.5
    y: 67
    z: 0.5
    yaw: 0
    pitch: 0
server-lobby: lobby
database:
  host: mongodb://root:root@localhost:27017/?authMechanism=SCRAM-SHA-256
  name: redbuild